### PR TITLE
Adds platform user route to delete private analytic

### PR DESCRIPTION
**Pull request by hoddr**

### CODE REVIEW

**Comment by brimoor** [comment]
@hoddr I propose that we also add support for uploading analytics in this branch too. Then I review as a whole once the backend implementation is finished and this can be tested.

**Comment by hoddr** [comment]
Does uploading analytics also include uploading the images?

**Comment by brimoor** [comment]
yes. platform users should be able to deploy a new analytic completely from the client libs.

A common pattern might be to deploy a new version of an analytic every week. Users will want to do that programmatically.

**Comment by hoddr** [comment]
@brimoor Please take a look at the routes. I want to make sure they are "pythonic" and I didn't miss any subtleties.

**Review by brimoor — APPROVED** [review]
LGTM.

I fixed one non-pythonic thing: use `requests.params` to pass parameters, don't manually construct URI. And added some missing documentation.

**Pull request merged**
